#!/usr/bin/python3
import os
import sys

os.system('curl https://us-central1-machine-learning-173502.cloudfunctions.net/pycall_ec2_shortcut?key=AccessKey&secret=SecretKey&region=ap-northeast-1&name=xxx&ops=start')

